# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_delete_producttwo'),
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='图形标题')),
                ('subtitle', models.CharField(max_length=50, null=True, verbose_name='图形子标题')),
                ('unit', models.CharField(max_length=10, verbose_name='数据点格式化后的单位, y轴格式化后的单位')),
                ('measurement', models.CharField(max_length=32, verbose_name='influx 表名')),
                ('auto_hostname', models.BooleanField(default=True, verbose_name='是否从业务线取主机名作为条件')),
                ('field_expression', models.CharField(max_length=100, null=True, verbose_name='influx sql where 条件')),
                ('tooltip_formatter', models.CharField(max_length=100, null=True, verbose_name='对tooltip进行格式化')),
                ('yaxis_formatter', models.CharField(max_length=100, null=True, verbose_name='对y轴进行格式化')),
                ('product', models.ManyToManyField(to='resources.Product', verbose_name='与业务线表多对多关联')),
            ],
            options={
                'db_table': 'monitor_influx_graph',
            },
        ),
    ]
