# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inception', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlworkflow',
            name='excute_result',
            field=models.TextField(null=True, verbose_name='执行结果返回的JSON'),
        ),
        migrations.AlterField(
            model_name='sqlworkflow',
            name='review_content',
            field=models.TextField(null=True, verbose_name='自动审核返回的JSON'),
        ),
        migrations.AlterUniqueTogether(
            name='masterconfig',
            unique_together=set([('cluster_name', 'db_name')]),
        ),
    ]
