# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inception', '0002_auto_20171110_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlworkflowstatus',
            name='status_code',
            field=models.CharField(default='dsh', max_length=10, verbose_name='工单状态代码'),
        ),
    ]
