# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inception', '0004_auto_20171110_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlworkflow',
            name='is_split',
            field=models.CharField(choices=[(0, '否'), (1, '是')], default=0, max_length=10, verbose_name='是否切分sql'),
        ),
    ]
