# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_auto_20170924_2115'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='serverstatus',
            managers=[
            ],
        ),
    ]
