# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_auto_20170924_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=32, verbose_name='业务线')),
                ('module_letter', models.CharField(db_index=True, max_length=10, verbose_name='字母简称')),
                ('op_interface', models.CharField(max_length=150, verbose_name='运维对接人')),
                ('dev_interface', models.CharField(max_length=150, verbose_name='业务对接人')),
                ('pid', models.IntegerField(db_index=True, verbose_name='上级业务线id')),
            ],
        ),
    ]
