# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_delete_producttwo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idc',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['pid']},
        ),
    ]
